# Generated by Django 4.1.2 on 2022-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_price', models.CharField(max_length=30)),
                ('project_images', models.ImageField(upload_to='images/file')),
                ('server_site', models.CharField(max_length=100)),
                ('Client_Side', models.CharField(max_length=100)),
                ('DataBase', models.CharField(max_length=100)),
                ('project_desc', models.CharField(max_length=150)),
            ],
        ),
    ]
