# Generated by Django 4.1.2 on 2022-10-22 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_projects_ideas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Mobile', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
