# Generated by Django 4.1.2 on 2022-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_details',
            name='project_Files',
            field=models.FileField(null=True, upload_to='important'),
        ),
    ]
